'use strict';
const E=require('./engine.cjs');
const assert=E.ensure;
function audit(l,text){l.audit.unshift({at:new Date().toISOString(),text});}
function vision(l,d){const {m}=E.findMatch(l,d.matchId),links={};for(const k of ['summary','replay','livestream','analytics'])if(d[k]){const url=new URL(d[k]);assert(['http:','https:'].includes(url.protocol),'Vision links must be HTTP(S).');links[k]=url.href;}m.vision={rosaMatchId:E.clean(d.rosaMatchId),links};}
function scheduleGroup(l,d,actor){const r=E.current(l),ms=r?.matches.filter(m=>m.groupId===d.groupId&&m.status==='scheduled');assert(r?.status==='active'&&ms.length,'No unstarted fixtures in this group.');assert(ms.every(m=>!m.binding),'Release the scoring session before moving bound fixtures.');ms.forEach(m=>{m.scheduledAt=null;m.court=null;m.proposal=null;});let at=Date.parse(d.at);for(const m of ms){E.propose(l,m.id,{at:new Date(at).toISOString(),court:d.court},actor);at+=(m.duration+r.rules.restMinutes)*60000;}r.groups.find(g=>g.id===d.groupId).schedulingIssue=null;audit(l,`Group ${r.groups.find(g=>g.id===d.groupId).level}: remaining fixtures rescheduled together.`);}
function unbind(l,d){const {r,m}=E.findMatch(l,d.matchId);assert(r.status==='active'&&m.binding&&E.clean(d.reason).length>=3,'Select a bound fixture and give a release reason.');const b=m.binding;const ms=r.matches.filter(x=>x.binding?.court===b.court&&x.binding?.sessionId===b.sessionId);assert(ms.every(x=>x.status==='scheduled'),'This session has scored fixtures. Finish or resolve it before releasing.');ms.forEach(x=>x.binding=null);audit(l,`Court session released: ${E.clean(d.reason,500)}`);}
function reschedule(l,data){
 const r=data.roundId?l.rounds.find(r=>r.id===data.roundId):E.current(l);assert(r?.status==='active','Select an active round.');
 const config=E.rules({...r.rules,...data.rules});assert(config.format===r.rules.format,'Round format cannot change.');
 const saved=r.matches.filter(m=>m.status!=='scheduled'||m.binding);
 assert(saved.every(m=>!m.court||config.courts.includes(m.court)),'A removed court has a scored or bound fixture. Keep it in the pool and exclude it from session availability instead.');
 if(data.startDate){E.rules({...config,startDate:data.startDate});r.startDate=data.startDate;}
 r.rules=config;r.deadline=E.zoned(E.addDays(r.startDate,config.deadlineDays),'23:59',config.timezone);
 for(const m of r.matches.filter(m=>m.status==='scheduled'&&!m.binding)){m.scheduledAt=null;m.court=null;m.session=null;m.proposal=null;}
 E.schedule(l,r);audit(l,`Round ${r.number} schedule rebuilt. Scored and bound fixtures preserved.`);
}
function changeRoster(l,d){
 if(['add','withdraw','restore'].includes(d.kind)&&l.nextGroups){delete l.nextGroups;audit(l,'Prepared group allocation cleared because the active roster changed.');}
 if(d.kind==='add'){
  const status=l.status;l.status='registration';let e;try{e=E.addEntrant(l,{names:d.names});}finally{l.status=status;}e.rating=Number(d.rating)||0;e.active=true;audit(l,`${e.name} added to the pool for a future round.`);return e;
 }
 const e=l.entrants.find(e=>e.id===d.id);assert(e,'Entry not found.');
 if(d.kind==='withdraw'){e.active=false;audit(l,`${e.name} withdrawn from future rounds. Published fixtures retained.`);}
 if(d.kind==='restore'){e.active=true;audit(l,`${e.name} restored to the next-round pool.`);}
 if(d.kind==='rename'){assert(Array.isArray(d.names)&&d.names.length===e.players.length&&d.names.every(n=>E.clean(n).length>=2),'Enter the player names.');e.players.forEach((p,i)=>p.name=E.clean(d.names[i]));e.name=e.players.map(p=>p.name).join(' / ');audit(l,`Player record updated: ${e.name}`);}
}
function reorder(l,ids){assert(l.status==='registration','Initial seeds are locked after the season starts.');assert(ids.length===l.entrants.length&&new Set(ids).size===ids.length&&ids.every(id=>l.entrants.some(e=>e.id===id)),'Include every entry once.');ids.forEach((id,i)=>l.entrants.find(e=>e.id===id).seed=i+1);}
function setNextGroups(l,groups){assert(Array.isArray(groups)&&groups.length&&groups.every(g=>Array.isArray(g)&&g.length===4),'Every group must contain four entries.');const ids=groups.flat();assert(new Set(ids).size===ids.length&&ids.every(id=>l.entrants.some(e=>e.id===id&&e.active!==false)),'Use each active entry at most once.');assert(l.entrants.filter(e=>e.active!==false).every(e=>ids.includes(e.id)),'Include all active entries or withdraw the entries sitting out.');l.nextGroups=groups;audit(l,'Organizer prepared the next round groups.');}
function applyGroups(l,groups){const r=E.current(l);assert(r?.status==='active'&&r.matches.every(m=>m.status==='scheduled'&&!m.binding),'Current groups can only be rebuilt before any scoring or binding.');setNextGroups(l,groups);const next=l.nextRules;l.rounds.pop();l.nextRules={...r.rules,startDate:E.addDays(r.startDate,-(r.number-1)*r.rules.intervalDays)};E.generateRound(l,groups);if(next)l.nextRules=next;l.nextGroups=null;audit(l,'Current round groups rebuilt by organizer.');}
function resume(l){assert(l.status==='needs-roster','This league is not awaiting a roster repair.');const groups=l.nextGroups||activeGroups(l);assert(groups,'Complete groups of four before continuing.');E.generateRound(l,groups);l.nextGroups=null;l.status='active';}
function activeGroups(l){const entries=l.entrants.filter(e=>e.active!==false);if(entries.length<4||entries.length%4)return null;const ranks=Object.fromEntries(E.ranking(l).map(e=>[e.id,e.rank]));entries.sort((a,b)=>(ranks[a.id]||a.seed)-(ranks[b.id]||b.seed));return Array.from({length:entries.length/4},(_,i)=>entries.slice(i*4,i*4+4).map(e=>e.id));}
function correct(l,d){const {r,m}=E.findMatch(l,d.matchId);assert(E.clean(d.reason).length>=3,'Give a correction reason for the audit history.');assert(r.status==='active','Closed-round corrections require a deliberate season rollback; this action only changes the active round.');const prior=m.score;m.status='scheduled';E.submit(l,m.id,d.score,{id:d.actorId,organizer:true},'organizer');audit(l,`Score corrected from ${prior?.join('–')||'pending'}: ${d.reason}`);}
function projections(l){for(const r of l.rounds){const courts=[...new Set(r.matches.map(m=>m.court).filter(Boolean))];for(const court of courts){let ready=null;for(const m of r.matches.filter(m=>m.court===court&&m.scheduledAt).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt))){if(m.status==='official'){if(m.completedAt&&Math.abs(Date.parse(m.completedAt)-Date.parse(m.scheduledAt))<86400000)ready=Date.parse(m.completedAt)+r.rules.restMinutes*60000;continue;}const planned=Date.parse(m.scheduledAt);m.estimatedAt=new Date(ready===null?planned:Math.max(ready,planned)).toISOString();ready=Date.parse(m.estimatedAt)+(m.duration+r.rules.restMinutes)*60000;}}}return l;}
function evidence(l,eid,through){const e=l.entrants.find(e=>e.id===eid);assert(e,'Entry not found.');return {name:e.name,rounds:l.rounds.filter(r=>r.status==='complete'&&r.number<=through).map(r=>({number:r.number,...r.summary[eid],matches:r.matches.filter(m=>m.entrySides.flat().includes(eid)).map(m=>({id:m.id,sides:m.sides.map(side=>side.map(p=>E.playerName(l,p))),score:m.score,source:m.source,completedAt:m.completedAt}))}))};}
module.exports={audit,vision,scheduleGroup,unbind,reschedule,changeRoster,reorder,setNextGroups,applyGroups,resume,activeGroups,correct,projections,evidence};
